### ISSUE TITLE
programing step

### ISSUE THREAD

**Issue by warehouseElc** [Winkelkatze/jbc_nano_solder#3]
i want to ask about programing method you used,
what programing software and hardware. of course the OS are you using ?
i'm not familar with stm32, but i know the basic.

**Comment by Winkelkatze** [comment]
This project runs on a STM32F030, this is one of the smallest (if not the smallest) STM32 controller. The software is based on libopencm3, which is a more compact alternative to the official CubeHAL from ST.

About the *how* I developed the firmware, I use the "classic" approach by using a text editor for writing code and a Makefile for compiling everything using the arm toolchain (arm-none-eabi-gcc). I've only tested this on Linux, but I might be possible to do the same thing with Cygwin or WSL on Windows.
The programmer itself is one of these cheap as STLink clones which I use together with OpenOCD. And sometimes I also use the embedded serial bootloader for flashing STM32.

**Comment by warehouseElc** [comment]
thanks for replying my post, i just finish board assembley still waiting for handle and tip.
a bit confuse about selecting compiler, what should i buy ?
should it work with a generic stlink ?

if any exist video will help me very much. one more question, the At24cs01 is out of stock I can't find it, so i replace with at24c01, i confuse about pin a0,a1,a2 and i'm not connect it to anywhere.

**Comment by Winkelkatze** [comment]
I don't know of any video to help you, but what you will need is the ARM toolchain (arm-none-eabi-gcc), git and make. I'm sure you can find install instructions for this on the internet.
Then you can simply follow the "Building the firmware" instructions from my README. This will produce a .elf file which can be flashed to the controller by various means. If you also install openocd it should be as simple as running "make flash" but there is also plenty information available how to get a .elf to your controller.

About the EEPORM, the at24c01 one should be fully compatible. I'm a bit confused about the address pins, did you change the footprint to a 8 pin variant? If so, the address pins need to be tied to ground. The 5 pin variant doesn't have these pins and they are bonded to ground internally.

**Comment by warehouseElc** [comment]
i found some tutor in internet, hope that methode will working, first we need to compile to elf and secondly upload to the board right ?
is there any button i have to press before or during upload ?

i didnt make any changes of footprint, just making an adapter with protoboard and put in at oled pinout in series with oled display because it use same pinout i think it should work.

**Comment by Winkelkatze** [comment]
Yes, its easiest to do this as two separate steps. For flashing, if you use the STLINK, you don't need to press any button.

If you decide to use the serial bootloader, you first need to bring the controller into the boor mode by holding the BOOT button while it starts. So press and hold boot while you also press RESET briefly. You can then use "stm32flash" (https://sourceforge.net/p/stm32flash/wiki/Home/) to write the firmware to the controller. If you choose this approach, don't forget to convert the .elf into binary first with "arm-none-eabi-objcopy -O binary firmware.elf firmware.bin".

Cool solution for the eeprom by the way :)

**Comment by warehouseElc** [comment]
I think the first methode is more easy, i was install like you said and confirm that was a build.elf after i build the firmware. at openOCD command i test make flash and its says no stlink detect.
unfortunately i don't have stlink, maybe i'll buy a cheap clone one, so before thats arrive i still have a time to learn the firmware. 

for the eeprom just use the easy way, thanks for helping.
one question, is possible with memory size to add a buzzer feature ?

**Comment by Winkelkatze** [comment]
Cool that it works so far.

About the buzzer, this should be possible since there is still about 600 bytes free.

**Comment by warehouseElc** [comment]
![IMG20220913161641](https://user-images.githubusercontent.com/39308038/189872397-c4a1b2c9-6817-4dbd-97aa-edfcc6fd4c4f.jpg)
update : its work but i dont know how to test eeprom, its seems works fine to save data setting. a bit confuse about datasheet at24c01n, some have address pin and the other said no internal conection. so i leave it open

still waiting tip for next update

**Comment by Winkelkatze** [comment]
Nice board :)

About the EEPROM address pins, normally they should be tied to ground. But if it also works like this, they may have internal pull-downs so you could also let them floating. As long as its keeping the settings and the last set temperature, the eeprom is working fine.

**Comment by Winkelkatze** [comment]
I just realized, that one value from the schematic was wrong. R5 should be 5K instead of 10K, to set the gain for the thermocouple to 501 (instead of the original 1001). I also added this value as a constant in main.c ("THERMOCOUPLE_GAIN").

If you don't have a 5k resistor at hand, you can just stack two 10k resistors, or use a slightly different value and adjust the THERMOCOUPLE_GAIN in main.c

**Comment by warehouseElc** [comment]
today my Chinese 115 it has 3,1 ohm resistance.
it hot like it should. i didn't understand how the code works, i set to 110c it raise to 160c and go to 110. is it working correctly ?
![Screenshot_2022-09-21-12-32-18-59](https://user-images.githubusercontent.com/39308038/191422427-5487ea2f-298e-42c1-a0df-670859d0c8bd.png)
![Screenshot_2022-09-21-12-32-32-85](https://user-images.githubusercontent.com/39308038/191422450-ddc328c7-105d-4423-bcdd-9d9c59db1d2d.png)

test attempt :
https://youtube.com/shorts/bmlzIEi-Sfc?feature=share

**Comment by Winkelkatze** [comment]
It should not do that. My build does not overshoot more than 5 degrees when turning on.
I see two possible causes for such behavior:

Cause 1: The outlier detection code for filtering the measured temperature is causing problems.
Maybe for some reason the temperature measurement in your setup is very noisy.
You can test that by adding a "return true;" to the first line of the "outlier_detection" function (Line 519 in main.c) The temperature control should still work like this, but the displayed temperature may be a bit unstable and the out-of-stand idle detection may not work.

Cause 2: The tip you are using has a much worse thermal coupling between the heater and the sensor.
All my tips react almost immediately to power changes. Meaning if the heater is turned OFF, the temperature immediately stops rising. It is possible, since you are using some non-original tips that the thermocouple lags behind the heater, which makes the control highly unstable. Increasing the "Reg wnd size" (In the Menu, in the "Heater controller" settings) to a higher value may help. This will slightly degrade the response to temperature changes though.

If you want to experiment with different control algorithms, the controller is implemented in "dma1_channel1_isr" (main.c)

**Comment by warehouseElc** [comment]
thanks i'll try your guide.
oh yes forget to tell i was lazy to hook up with a good smps, so i connect it to linear ps, maybe that cause the trouble.

**Comment by warehouseElc** [comment]
i think is not ps issue, like you said it cause by non original tips, overall working perfectly accept start up temp. any idea how to solve that ? i try increase reg wnd size at 30c it's working, but not much.

results what i get after increase reg wnd size :
at 150c it overshoot to 200c
at 200c > 235c
at 300c > 325c
at 350c > 365c

it's like the higher temp is more stable, but at low temp is much worse. it happens only when i turn on the heater accept that no overshoot at all.

i really need this to working with non-original jbc tips, you know the price can be a double, and still hard to find suppliers at my country.

(temp stable noise)
![IMG20220922163857](https://user-images.githubusercontent.com/39308038/191714406-ddcd9afa-afc4-4564-9722-8685ca1a9e49.jpg)

(start up noise)
![IMG20220922164020](https://user-images.githubusercontent.com/39308038/191714650-50646329-6a1b-45b5-beec-f93b9c856753.jpg)

**Comment by Winkelkatze** [comment]
The only real way to solve that issue is by adjusting the controller. At the moment, the control algorithm is mainly a proportional approach with a small integral component.
I did it that way, since it worked perfectly for me. The tips you are using make the control more difficult, but I'm almost certain by implementing a proper PID control this could be solved.

**Comment by Winkelkatze** [comment]
If you don't want to dig into controller design, I have a few alternative options for you which you might want to try:

Reducing the power limit ("Heater controller" -> "Max PWM duty") will definitely help.

You could try is to increase the P controllers window (Reg wnd size) even more and also increase the I controllers limit (Int. ofs limit). You need to adjust the limits in menu.c for that.
This makes the controller less aggressive which should solve overshooting.

One general remark though, even with the best control algorithms, the delay caused by the tip will always result in a slower response time and worse performance while soldering.

**Comment by warehouseElc** [comment]
i already figured it out and did like you suggested, incrase the pwm periode about 25ms and incrase the reg wnd size limit in menu.c after the test yesterday, now no more over shoot.
is it PID control, right ?
if P = reg wnd size 
and I = int. ofs
so what we call D in your design?

i also have issue with encoder, it jump 2 step.
should it work if i fix debounce at input.c incrase or decrease the tick ?

thanks for spending your time in this thread.
it's a great controller for nano and also good job for the hardware and software. if you have a time please update the firmware with a buzzer, its so complicated for me.

**Comment by Winkelkatze** [comment]
No, its a PI controller without differential (D) part. You are correct, that the "Int. ofs" (short for Integral offset) is the integral part. However, this is not implemented as a traditional P-I controller where P gets zero during stable operation. The 'I' part rather slightly offsets the target for the P controller so we reach the target.
But yes, "reg wnd size" (Regulation window size) sets the inverse gain for the P controller, so P = 1 / "reg wnd size".

About the encoder issue, seems like there are different types of encoders. The one I use makes two signal steps (phase changes) per physical / haptic step (detent). So that's why I implemented it this way. Maybe your encoder works differently. Could also be a contact bouncing issue, so you can also try to increase the debounce value.

**Comment by warehouseElc** [comment]
now i get it, i've to calibrate with that way.

thanks, i'll try incrasing debounce value.
pin uart its for programing or debug ? or both function will work ? cause i didnt see any serial out at the firmware.
